# Generated by Django 6.0.1 on 2026-01-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_model')),
            ],
        ),
        migrations.CreateModel(
            name='patient_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('emg_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.doctor_model')),
            ],
        ),
        migrations.CreateModel(
            name='patient_record_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=150)),
                ('prescription', models.CharField(max_length=150)),
                ('created_date', models.DateField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.patient_model')),
            ],
        ),
    ]
